### PR TITLE
initial migration to Franklin.jl

### PR DESCRIPTION
**Pull request by pdimens**
While there's still work to do, this PR is the first steps towards migrating EcoJulia's site towards a Franklin.jl based approach.
Todos:
- Publications page formatting
- Related Packages page formatting
- Consensus on graphics for the homepage packages
- Consensus on graphics for EcoJulia and EcoBase.jl
- Setup GitHub Actions auto-deployment outlined [here](https://franklinjl.org/workflow/deploy/index.html#deploying_on_github)

### CODE REVIEW

**Comment by mkborregaard** [comment]
This is great @pdimens ! I've given you push rights to this repo - feel free to merge when ready.

**Comment by pdimens** [comment]
Thanks! Can I please get access to the settings so I can setup the token for auto-CI building/deploying? That access can be temporary, or someone with that access can follow the instructions [here](https://franklinjl.org/workflow/deploy/index.html#adding_access_tokens) and notify me when it's done.

**Comment by mkborregaard** [comment]
I've tried to follow the instructions now - let me know if I f*cked up somehow

**Comment by pdimens** [comment]
You in fact, did not f*ck up, it's live! :grin: 
Thanks!

**Comment by mkborregaard** [comment]
There's a first for everything I guess :-)
Awesome work!

**Comment by pdimens** [comment]
Just kidding, it built once and now it says access denied. Did you setup the key for email `git@github.com` ?

Have a look at the Actions failed deployment to see whats up. I had an issue like that with PopGen.jl's docs via Docusaurus and the issue was that the account for the token had to be `git@github.com`

**Comment by mkborregaard** [comment]
seems fixed now?

**Comment by pdimens** [comment]
Seems all well and good now. Did you actually change anything or am I losing my mind?

**Comment by mkborregaard** [comment]
No I did exactly what you suggested :-)

**Comment by pdimens** [comment]
Awesome, thanks! Hopefully smooth sailing from here.

**Pull request merged**
